from typing import Any, Optional, Dict
from fastapi import status
from pydantic import BaseModel, Field


class ProblemDetails(BaseModel):
    type: str = Field(
        default = "about:blank",
        description="A URI reference identifying the problem type.",
    )
    title: str = Field(
        ..., description="Short summary of the problem type."
    )
    status: int = Field(
        ..., description="HTTP status code generated by the server."
    )
    detail: str = Field(
        ..., description="Human-readable explanation specific to this occurrence."
    )
    instance: Optional[str] = Field(
        default=None, description="URI path identifying the specific request instance."
    )
    invalid_params: Optional[list[Dict[str, Any]]] = Field(
        default=None, description="Field-level validation error details."
    )


class DomainException(Exception):
    def __init__(self, message: str = "A domain error occurred."):
        self.message = message
        super().__init__(self.message)


class UserNotFoundException(DomainException):
    def __init__(self, message: str = "User not found"):
        super().__init__(message)


class UserAlreadyExistsException(DomainException):
    def __init__(self, message: str = "User already exists"):
        super().__init__(message)


class FolderNotFoundException(DomainException):
    def __init__(self, message: str = "Folder not found"):
        super().__init__(message)


class FolderAlreadyExistsException(DomainException):
    def __init__(self, message: str = "Folder already exists"):
        super().__init__(message)


class NoteNotFoundException(DomainException):
    def __init__(self, message: str = "Note not found"):
        super().__init__(message)


class LabelNotFoundException(DomainException):
    def __init__(self, message: str = "Label not found"):
        super().__init__(message)


class LabelAlreadyExistsException(DomainException):
    def __init__(self, message: str = "Label already exists"):
        super().__init__(message)

DOMAIN_EXCEPTION_MAP: dict[type[DomainException], tuple[int, str]] = {
    UserNotFoundException: (status.HTTP_404_NOT_FOUND, "User Not Found"),
    FolderNotFoundException: (status.HTTP_404_NOT_FOUND, "Folder Not Found"),
    NoteNotFoundException: (status.HTTP_404_NOT_FOUND, "Note Not Found"),
    LabelNotFoundException: (status.HTTP_404_NOT_FOUND, "Label Not Found"),
    UserAlreadyExistsException: (status.HTTP_409_CONFLICT, "User Already Exists"),
    FolderAlreadyExistsException: (status.HTTP_409_CONFLICT, "Folder Already Exists"),
    LabelAlreadyExistsException: (status.HTTP_409_CONFLICT, "Label Already Exists"),
    DomainException: (status.HTTP_400_BAD_REQUEST, "Bad Request"),
}